namespace Teleperformance.DataIngestion.Sharepoint.Constants;

public static class Constants
{
    public const string ConnectionStringMissing = "Connection string is not configured.";
    public const string ApplicationNotFound = "Application not found.";
    public const string ApplicationNameRequired = "Application name is required.";
    public const string ApplicationTypeNotRecognised = "Application type '{0}' is not recognised.";
    public const string CredentialsRequired = "TenantId, ClientId, ClientSecret, and HostName are required when no application is selected.";
    public const string SiteIdMissing = "Microsoft Graph did not return a site id.";
    public const string NoLibrariesAvailable = "No document libraries are available on the resolved site.";
    public const string LibraryNotFound = "Document library '{0}' was not found. Available: {1}";
    public const string ClientIdAndSecretRequired = "ClientId and ClientSecret are required.";
    public const string AuthNotConfigured = "Authentication is not configured on the server.";
    public const string InvalidClientCredentials = "Invalid client credentials.";
    public const string SigningKeyNotConfigured = "Auth signing key is not configured.";
    public const string FilePathRequired = "FilePath is required.";
    public const string ApplicationOwnerRequired = "Owner is required for application registration.";
    public const string ApplicationRegionRequired = "Region is required for client registration.";
    public const string ExternalSiteNameRequired = "SharePoint site name is required for external applications.";
    public const string InternalConnectivityApplicationNotConfigured = "Internal application credentials are not configured. Set sharepointinternaltenantid, sharepointinternalclientid, sharepointinternalclientsecret, and sharepointinternalhostname environment variables.";
    public const string ExternalSiteNotAccessible = "The internal application cannot access site '{0}'. Raise an access request for this site before registering it.";
    public const string ExternalSiteConnectivityVerified = "Site is reachable using the internal application.";
    public const string MissingApiVersionHeader = "Missing required header: x-tpdi-api-version";
    public const string ApplicationTokenHeadersRequired = "x-application-id (registered app GUID) and x-client-secret (API secret) headers are required.";
    public const string InvalidActiveStatus = "activeStatus must be 1 (active), 0 (inactive), or null (all).";
    public const string PostFilePathRequired = "filePath is required in the JSON body, e.g. {\"filePath\":\"Documents/video.mp4\"}.";
    public const string QueryFilePathRequired = "File path is required. Use ?path={filePath} or ?path64={base64url}, or POST /workspace/file with a JSON body.";
    public const string MissingOrInvalidAuthorizationHeader = "Missing or invalid Authorization header. Expected: Bearer {token}";
    public const string MissingAuthorizationHeader = "Missing Authorization header. Expected: Bearer {token}";
    public const string MissingToken = "Missing token. Use Authorization: Bearer {token} or ?access_token={token}";
    public const string InvalidOrExpiredToken = "Invalid or expired token.";
    public const string ConnectivityHostNameRequired = "Host name is required when verifying connectivity with application credentials.";
    public const string ConfiguredApplicationSiteNotFound = "The configured SharePoint application site was not found.";
    public const string TokenAccessTokenMissing = "Token response missing access_token.";
    public const string DestinationFolderPathRequired = "Destination folder path is required.";
    public const string SourceFileItemNotFound = "Cannot find file item for path: {0}";
    public const string FolderIdNotFound = "Cannot read folder id for path: {0}";
    public const string DestinationFolderNotResolved = "Could not resolve destination folder: {0}";
    public const string CreatedFolderIdMissing = "Created folder '{0}' but could not read its ID.";
    public const string GraphApiSearchError = "Graph API Search Error: {0}";
    public const string SuccessMessage = "Success";
    public const string SharePointApplicationIdMissing = "SharePointApplicationIdMissing";
    public const string SharePointSourcePathMissing = "SharePointSourcePathMissing";
    public const string MoveToProcessedFailed = "MoveToProcessedFailed";
    public const string MoveToProcessedError = "MoveToProcessedError";
    public const string MovedToProcessed = "MovedToProcessed:{0}/{1}";
    public const string MissingConfigurationId = "Missing configurationId";
    public const string SecurityGroupNotFound = "Security group not found.";
    public const string UnableToRetrieveAccess = "Unable to retrieve access.";
    public const string InvalidOrMissingSharePointFile = "Invalid or missing SharePoint file";
}
